### ISSUE TITLE
SolrCloud in ECS setup is fragile

### ISSUE THREAD

**Issue by eefahy** [hybox/aws#105]
When doing upgrades or rebuilds of the SolrCloud instances, the ECS cluster service will hang when trying to run the container task. (Error mesage is something about the containers having insufficient memory) In order to unstick the service, someone needs to log into the instances and run `docker stop <dockerid>` which will trigger a restart of the container via the ECS daemon. The service will then recover cleanly and complete the stack update fine, however that doesn't mean SolrCloud actually started up cleanly. To ensure that, check the logs via `docker logs <dockerid>` and if needed run `docker stop <dockerid>` again.

**Comment by bbranan** [comment]
The move to deployment of SolrCloud via Beanstalk (possibly without Docker) rather than EBS should lessen this fragility. See issue #126.
