### ISSUE TITLE
Convert CloudFormation templates to YAML

### ISSUE THREAD

**Issue by bbranan** [hybox/aws#118]
Convert the existing set of CloudFormation templates from the current JSON format to YAML. This will provide easier reading and allow for comments.

**Comment by eefahy** [comment]
blocked by https://github.com/hybox/aws/pull/116

- [ ] redo cfn-flip call for all json templates
- [ ] fix lambda coversions
- [ ] verify the stack builds

**Comment by eefahy** [comment]
Closed by 1d83bf7ea67b4ab98db2361fc17bc46d685e7f13
