### ISSUE TITLE
Support fcrepo optimizations around the many members problem (thanks, Danny B.!)

### ISSUE THREAD

**Issue by mjgiarlo** [hybox/aws#143]
See this post on hydra-community for more:

https://groups.google.com/forum/#!msg/hydra-community/0ugAJqJ8sMg/yN78DlmhBgAJ

> This recent commit introduces two optimizations:
https://github.com/fcrepo4/fcrepo4/commit/cd5b69e2b8e85f13651fe7e88e88c6d7154105c6
> 
> 1. You can turn on parallelization for the serialization of RDF responses by adding the following system property:
> `-Dfcrepo.streaming.parallel=true`
> 
> 2. You can increase the ModeShape cache by updating your `repository.json` file with a `cacheSize` element, as seen here:
> https://github.com/fcrepo4/fcrepo4/commit/cd5b69e2b8e85f13651fe7e88e88c6d7154105c6#diff-908fc2104ef2503fda27e7a3eb512f7fR8
> ** Note, this cache configuration can be put into use immediately, without requiring any updates beyond that to your `repository.json` file. Testing with various values of `cacheSize` are documented in the wiki:
> https://wiki.duraspace.org/display/FF/Many+Members+Performance+Testing

(Thanks for your work on this, @dbernstein!)

**Comment by bbranan** [comment]
Resolved as part of https://github.com/hybox/aws/pull/145. The fcrepo.streaming.parallel=true parameter was added. The latest fcrepo repository.json files  (on master) include the cacheSize values set to 10000 by default, so pulling in the latest Fcrepo build resolves part 2.
