### ISSUE TITLE
Add parameter to disable open self-signup

### ISSUE THREAD

**Issue by bbranan** [hybox/aws#157]
Add a parameter that can be set to "true" or "false" for turning on/off open self-signup.

The parameter should set the environment variable SETTINGS__DEVISE__ACCOUNT_SIGNUP in the hyku webapp beanstalk config.

**Comment by bbranan** [comment]
Depends on https://github.com/samvera-labs/hyku/issues/1203

**Comment by mjgiarlo** [comment]
https://github.com/samvera-labs/hyku/issues/1203 is now closed.

**Comment by mjgiarlo** [comment]
Now blocked by https://github.com/samvera-labs/hyku/issues/1204
