### ISSUE TITLE
up to date solution stacks will break zookeeper iptables hack

### ISSUE THREAD

**Issue by eefahy** [hybox/aws#163]
Thanks to the work of @mbklein the fix (once we upgrade the solution stack to its current version) we will need to mimic his fix as seen here: https://github.com/avalonmediasystem/avalon-aws/commit/b5d217712072cf7c776e11c232c5f0c1ccdc5bf0

**Comment by bbranan** [comment]
@mbklein Noted his use of this solution stack `64bit Amazon Linux 2017.03 v2.7.0 running Docker 17.03.1-ce` with the linked fix.
