### ISSUE TITLE
CREATE TENANTS

### ISSUE THREAD

**Issue by maureenbianca** [hybox/aws#172]
Need help on getting started on hyku application. When I sign in am getting *You are not authorized to create tenants*

**Comment by bbranan** [comment]
I'm assuming you're running your own stack. This can be done in one of two ways:
1. Enable open tenant creation. Make sure this parameter is set:
   {
    "ParameterKey": "DisableOpenTenantCreation",
    "ParameterValue": "false"
   }
2. Set up a `Super Admin` account, which allows for tenant creation: https://github.com/samvera-labs/hyku/wiki/Give-tenant-user-admin-role
