### ISSUE TITLE
Running without a domain

### ISSUE THREAD

**Issue by cjhowe-us** [hybox/aws#175]
Is it possible to use this CloudFormation template without registering a domain? We only have AWS credit for our project so we can't register a domain.

**Comment by bbranan** [comment]
You won't be able to use the templates as they are without a domain, as there is an expectation that access will be provided through a subdomain for each tenant which is managed by Route53. That said, if you have AWS credits, you should be able to use them to register a domain through Route53: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/registrar.html

**Comment by cjhowe-us** [comment]
Ah yes, we tried it. Unfortunately, [it doesn't seem like credit will work with Route53 domain registration](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-register.html). Thanks for the quick response!
