### ISSUE TITLE
Cannot deploy due to outdated solution stack

### ISSUE THREAD

**Issue by cjhowe-us** [hybox/aws#177]
It looks like the CloudFormation template uses some Elastic Beanstalk solution stacks that are out of date. I am deploying to the `us-east-1` AWS region, and seeing the following error on deploy:

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/29269679/37779997-257b81ca-2dc4-11e8-9109-db53ff968053.png">

This error occurred under the "Hyku solr stack." Do you have any idea how we can fix this?

Thanks!

**Comment by bbranan** [comment]
Hi Christian,

I'd suggest taking a look at this PR, as you'll need to do something similar: https://github.com/hybox/aws/pull/81/files.

You can find the latest supported platforms for deployments in Beanstalk here: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html, or via the CLI: https://docs.aws.amazon.com/cli/latest/reference/elasticbeanstalk/list-available-solution-stacks.html

**Comment by cjhowe-us** [comment]
Hey, I made a PR to fix this. Please let me know what you think!
