### ISSUE TITLE
no DNS for  public hosted zone

### ISSUE THREAD

**Issue by tingletech** [hybox/aws#73]
Hi,

I don't control any DNS domain names.  They are all handled by another group in another AWS account.  Can I use this w/o a  public hosted zone?

Thanks -- Brian

**Comment by mjgiarlo** [comment]
:arrow_up: @eefahy @cbeer :grey_question:

**Comment by eefahy** [comment]
Ah, good question. Yeah, I think you could wrap the Route53 calls with conditionals to make those optional.

**Comment by tingletech** [comment]
I could not figure out how to execute the above suggestion -- but then I remembered an unused vanity domain name I own for a project that didn't materialize that I can use to test this.
