### ISSUE TITLE
hybox-deployment-artifacts S3 bucket

### ISSUE THREAD

**Issue by tingletech** [hybox/aws#77]
Is there any sensitive config info in `fcrepo-webapp-4.5.1.war` in the hybox-deployment-artifacts bucket? If not, would you consider making it world readable, or letting my account read it?

Right now, I'm getting a failure when the fcrepo stack tries to create itself.

> Unable to download from S3 location (Bucket: hybox-deployment-artifacts Key: fcrepo-webapp-4.5.1.war). Reason: You do not have permission to perform the 's3:GetObject' or 's3:ListBucket' action. Verify that your S3 policies and your ACLs allow you to perform these actions.

**Comment by tingletech** [comment]
```
aws s3 ls hybox-deployment-artifacts/fcrepo-webapp-4.5.1.war
2016-05-11 08:12:38   46257146 fcrepo-webapp-4.5.1.war
```

the bucket is open...  Not sure why it could not be read from the stack

**Comment by cbeer** [comment]
I don't think there's anything sensitive there (yet), but I think we expected each deployment to create their own bucket (documented in the README here: https://github.com/hybox/aws#travis-deployment-integration). 

At the very least, before making it public, the Hybox team needs to agree what our support for that store is going forward.

**Comment by tingletech** [comment]
Odd, I can read it from some of my shells -- but not all of my shells.  And if I ssh into the VPC that CF set up through the bastion, I can't read the bucket.

```
[registry@dsc-registry-stg ~]$ aws s3 ls hybox-deployment-artifacts/fcrepo-webapp-4.5.1.war
2016-05-11 08:12:38   46257146 fcrepo-webapp-4.5.1.war
[registry@dsc-registry-stg ~]$ aws s3 ls hybox-deployment-artifacts
                           PRE cloudformation/
                           PRE hybox/
                           PRE lambda/
                           PRE lerna/
2016-05-11 08:12:38   46257146 fcrepo-webapp-4.5.1.war
2016-05-26 14:54:16  128396427 fits-0.10.2.zip
2016-05-31 14:01:18  157933850 libreoffice5.1.zip
[registry@dsc-registry-stg ~]$ exit
logout
-bash-4.2$ aws s3 ls hybox-deployment-artifacts/fcrepo-webapp-4.5.1.war

A client error (AccessDenied) occurred when calling the ListObjects operation: Access Denied
```

from one of the zookeepers in the VPC

```
[ec2-user@ip-10-0-3-205 ~]$ aws s3 ls hybox-deployment-artifacts/fcrepo-webapp-4.5.1.war

An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
```

**Comment by tingletech** [comment]
that link does not really document how to create and populate that bucket.  _edit_ okay, I guess it does -- but I was sort of mislead by the fact that most of the bucket could be read.  I don't want a fork -- I was trying to run your template with the big "Launch Stack" button on your page:
<img width="538" alt="screen shot 2016-08-15 at 12 10 49 pm" src="https://cloud.githubusercontent.com/assets/227374/17676041/62635e28-62e1-11e6-9961-47971b273bfd.png">

**Comment by tingletech** [comment]
I'm just trying to get it running for a demo, so would not expect long term support of the bucket.

more info...

This URL gives Forbidden:
https://s3.amazonaws.com/hybox-deployment-artifacts/fcrepo-webapp-4.5.1.war

This URL returns a directory listing:
https://s3.amazonaws.com/hybox-deployment-artifacts/

```
[registry@dsc-registry-stg ~]$ aws s3 ls hybox-deployment-artifacts/fcrepo-webapp-4.5.1.war
2016-05-11 08:12:38   46257146 fcrepo-webapp-4.5.1.war
[registry@dsc-registry-stg ~]$ aws s3 cp s3://hybox-deployment-artifacts/fcrepo-webapp-4.5.1.war .
An error occurred (403) when calling the HeadObject operation: Forbidden
Completed 1 part(s) with ... file(s) remaining
```

So I would guess that everyone has 's3:ListBucket' but only your account has 's3:GetObject' 

I think setting up the travis CI and pushing to a bucket is out of scope for my experiment.

**Comment by tingletech** [comment]
All the CF json can be read -- I guess that I why I thought I would be able to read the entire bucket:  https://s3.amazonaws.com/hybox-deployment-artifacts/cloudformation/current/templates/slack.json

**Comment by tingletech** [comment]
`fcrepo-webapp-4.5.1.war` is the only file that cannot be read from the bucket.  I seem to be able to read all other files I've checked from the bucket.

I think if someone there ran `aws s3api put-object-acl --bucket hybox-deployment-artifacts --key fcrepo-webapp-4.5.1.war --acl public-read` I would be able to run the stack.

**Comment by tingletech** [comment]
Thanks @cbeer I was able to get past this error (and on to #78) when this file was made public!
