### ISSUE TITLE
S3 bucket access for fcrepo.war is forbidden

### ISSUE THREAD

**Issue by thatbudakguy** [hybox/aws#95]
Deployment with `$AWS_DEFAULT_REGION` set to `us-west-2` ultimately fails on the fcrepo stack:
```
Unable to download from S3 location (Bucket: hybox-deployment-artifacts Key: fcrepo-webapp-4.6.0.war). Reason: The bucket is in this region: us-east-1. Please use this region to retry the request
```
Must I deploy in `us-east-1`?

**Comment by thatbudakguy** [comment]
No dice; deploying in `us-east-1` gives:
```
Unable to download from S3 location (Bucket: hybox-deployment-artifacts Key: fcrepo-webapp-4.6.0.war). Reason: Forbidden
```

**Comment by eefahy** [comment]
We changed the permissions on that bucket so I think you should be able to deploy in `us-east-1` - However, I'm currently trying to build the stack in `us-west-2` and am finding that I cannot get to the `hybox-deployment-artifacts` bucket to build the stack.

**Comment by eefahy** [comment]
Closing as the bucket is available in `us-east-1` - changes re: ablity to deploy to other regions forthcoming.
